{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f31cb4d4-5d11-450a-8d4f-31b28aed9dc8",
   "metadata": {},
   "source": [
    "<div class=\"alert alert-block alert-info\"> <b>NOTE</b> Please select the kernel <code>Python [conda env:gnn-tf]</code> for this notebook. </div>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dc192179-b3be-4253-b138-8101ef811366",
   "metadata": {},
   "source": [
    "# 2. Inference - Segmentation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ad52d108-e300-4e94-86bd-c7c633c83ff6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import re\n",
    "import subprocess"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "76463f3d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-07-09 16:32:34.524997: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "711afecc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-07-09 16:32:37.646425: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2024-07-09 16:32:37.647893: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2024-07-09 16:32:37.695827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: \n",
      "pciBusID: 0000:01:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.696525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: \n",
      "pciBusID: 0000:23:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.697077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 2 with properties: \n",
      "pciBusID: 0000:41:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.697619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 3 with properties: \n",
      "pciBusID: 0000:61:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.698165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 4 with properties: \n",
      "pciBusID: 0000:81:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.698703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 5 with properties: \n",
      "pciBusID: 0000:a1:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.699238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 6 with properties: \n",
      "pciBusID: 0000:c1:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.699773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 7 with properties: \n",
      "pciBusID: 0000:e1:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:32:37.699789: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "2024-07-09 16:32:37.719850: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11\n",
      "2024-07-09 16:32:37.719902: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11\n",
      "2024-07-09 16:32:37.722755: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10\n",
      "2024-07-09 16:32:37.722996: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10\n",
      "2024-07-09 16:32:37.723250: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory\n",
      "2024-07-09 16:32:37.723933: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11\n",
      "2024-07-09 16:32:37.724009: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory\n",
      "2024-07-09 16:32:37.724019: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n",
      "Skipping registering GPU devices...\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tf.config.list_physical_devices('GPU')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "166cbd8a-02de-4d8c-aec0-2db2e5829e39",
   "metadata": {},
   "outputs": [],
   "source": [
    "software_dir = 'software'\n",
    "data_dir = 'ctc-data/pred-seg'\n",
    "\n",
    "models = [\n",
    "    'Fluo-N2DL-HeLa'\n",
    "]\n",
    "\n",
    "pattern = re.compile('\\d{3}')\n",
    "data_ids = [f for f in os.listdir(os.path.join(data_dir, models[0])) if pattern.fullmatch(f)]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5a16b848-fe0a-4ede-bb27-605e0cd14773",
   "metadata": {},
   "source": [
    "Predict segmentations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4a6a6dd8-59a6-4f34-8562-74c99cdf0bc0",
   "metadata": {},
   "outputs": [],
   "source": [
    "fov = '25'\n",
    "min_size = '10'\n",
    "max_size = '1000000'\n",
    "edge_dist = '2'\n",
    "sigmoid_thresh = '0.4'\n",
    "min_center_size = '5'\n",
    "pre_sequence_frames = '4'\n",
    "data_format = 'NCHW'\n",
    "\n",
    "code_seg = os.path.join(software_dir, 'seg_code/new_version')\n",
    "seg_model_dir = os.path.join(software_dir, 'parameters/Seg_Models')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f785ad68-2589-4975-a667-46a7df3ff408",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "------ Fluo-N2DL-HeLa ------\n",
      "001\n",
      "2024-07-09 16:23:38: Restored from software/parameters/Seg_Models/Fluo-N2DL-HeLa/model.ckpt\n",
      "Done!\n",
      "2024-07-09 16:23:39: Done\n",
      "2024-07-09 16:23:36.663970: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "2024-07-09 16:23:38.114441: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2024-07-09 16:23:38.115316: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2024-07-09 16:23:38.158826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: \n",
      "pciBusID: 0000:01:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:23:38.158857: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "2024-07-09 16:23:38.186980: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11\n",
      "2024-07-09 16:23:38.187029: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11\n",
      "2024-07-09 16:23:38.191063: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10\n",
      "2024-07-09 16:23:38.191379: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10\n",
      "2024-07-09 16:23:38.191618: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/cv2/../../lib64:\n",
      "2024-07-09 16:23:38.192491: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11\n",
      "2024-07-09 16:23:38.192573: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/cv2/../../lib64:\n",
      "2024-07-09 16:23:38.192582: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n",
      "Skipping registering GPU devices...\n",
      "2024-07-09 16:23:38.192839: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-07-09 16:23:38.200881: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2024-07-09 16:23:38.200907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:\n",
      "2024-07-09 16:23:38.200914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      \n",
      "2024-07-09 16:23:38.300189: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n",
      "2024-07-09 16:23:38.317865: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2450210000 Hz\n",
      "Traceback (most recent call last):\n",
      "  File \"software/seg_code/new_version/Inference2D.py\", line 410, in <module>\n",
      "    inference()\n",
      "  File \"software/seg_code/new_version/Inference2D.py\", line 87, in inference\n",
      "    _, image_softmax, center_sigmoid, _ = model(image, training=False)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 1012, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/msschwar/Caliban-2023_Schwartz_et_al/benchmarking/CellTrackerGNN/software/seg_code/new_version/Networks.py\", line 254, in call\n",
      "    out_down, out_skip = down_layer(out_down, training=training, mask=mask)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 1012, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/msschwar/Caliban-2023_Schwartz_et_al/benchmarking/CellTrackerGNN/software/seg_code/new_version/Networks.py\", line 70, in call\n",
      "    conv = conv_layer(activ)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 1012, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py\", line 248, in call\n",
      "    outputs = self._convolution_op(inputs, self.kernel)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py\", line 201, in wrapper\n",
      "    return target(*args, **kwargs)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 1020, in convolution_v2\n",
      "    name=name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 1150, in convolution_internal\n",
      "    name=name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 2604, in _conv2d_expanded_batch\n",
      "    name=name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py\", line 932, in conv2d\n",
      "    _ops.raise_from_not_ok_status(e, name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 6862, in raise_from_not_ok_status\n",
      "    six.raise_from(core._status_to_exception(e.code, message), None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "tensorflow.python.framework.errors_impl.UnimplementedError: The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW [Op:Conv2D]\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.2.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.2.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.state_spec\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.state_spec\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.state_spec\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.2.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.2.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.cell.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.cell.recurrent_kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.cell.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.cell.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.cell.recurrent_kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.cell.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.cell.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.cell.recurrent_kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.cell.bias\n",
      "WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.\n",
      "\n",
      "\n",
      "002\n",
      "2024-07-09 16:23:42: Restored from software/parameters/Seg_Models/Fluo-N2DL-HeLa/model.ckpt\n",
      "Done!\n",
      "2024-07-09 16:23:43: Done\n",
      "2024-07-09 16:23:40.516280: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "2024-07-09 16:23:42.012816: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2024-07-09 16:23:42.014026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1\n",
      "2024-07-09 16:23:42.059424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: \n",
      "pciBusID: 0000:01:00.0 name: NVIDIA RTX A6000 computeCapability: 8.6\n",
      "coreClock: 1.8GHz coreCount: 84 deviceMemorySize: 47.54GiB deviceMemoryBandwidth: 715.34GiB/s\n",
      "2024-07-09 16:23:42.059450: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0\n",
      "2024-07-09 16:23:42.084319: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11\n",
      "2024-07-09 16:23:42.084381: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11\n",
      "2024-07-09 16:23:42.087843: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10\n",
      "2024-07-09 16:23:42.088101: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10\n",
      "2024-07-09 16:23:42.088347: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/cv2/../../lib64:\n",
      "2024-07-09 16:23:42.089119: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11\n",
      "2024-07-09 16:23:42.089195: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/cv2/../../lib64:\n",
      "2024-07-09 16:23:42.089209: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n",
      "Skipping registering GPU devices...\n",
      "2024-07-09 16:23:42.089694: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-07-09 16:23:42.098654: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\n",
      "2024-07-09 16:23:42.098691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:\n",
      "2024-07-09 16:23:42.098698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      \n",
      "2024-07-09 16:23:42.200432: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)\n",
      "2024-07-09 16:23:42.217832: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2450210000 Hz\n",
      "Traceback (most recent call last):\n",
      "  File \"software/seg_code/new_version/Inference2D.py\", line 410, in <module>\n",
      "    inference()\n",
      "  File \"software/seg_code/new_version/Inference2D.py\", line 87, in inference\n",
      "    _, image_softmax, center_sigmoid, _ = model(image, training=False)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 1012, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/msschwar/Caliban-2023_Schwartz_et_al/benchmarking/CellTrackerGNN/software/seg_code/new_version/Networks.py\", line 254, in call\n",
      "    out_down, out_skip = down_layer(out_down, training=training, mask=mask)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 1012, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/msschwar/Caliban-2023_Schwartz_et_al/benchmarking/CellTrackerGNN/software/seg_code/new_version/Networks.py\", line 70, in call\n",
      "    conv = conv_layer(activ)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 1012, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py\", line 248, in call\n",
      "    outputs = self._convolution_op(inputs, self.kernel)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py\", line 201, in wrapper\n",
      "    return target(*args, **kwargs)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 1020, in convolution_v2\n",
      "    name=name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 1150, in convolution_internal\n",
      "    name=name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py\", line 2604, in _conv2d_expanded_batch\n",
      "    name=name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py\", line 932, in conv2d\n",
      "    _ops.raise_from_not_ok_status(e, name)\n",
      "  File \"/home/msschwar/miniforge3/envs/gnn-tf/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 6862, in raise_from_not_ok_status\n",
      "    six.raise_from(core._status_to_exception(e.code, message), None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "tensorflow.python.framework.errors_impl.UnimplementedError: The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW [Op:Conv2D]\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.2.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.Conv.2.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).BinaryOutputLogits.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.0.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.state_spec\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.state_spec\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.state_spec\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.0.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.1.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.2.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.0.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.0.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.1.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.1.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.2.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.Conv.2.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.0.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.axis\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.gamma\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.beta\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.moving_mean\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).UpLayers.3.BN.1.moving_variance\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.cell.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.cell.recurrent_kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.1.ConvLSTM.0.cell.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.cell.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.cell.recurrent_kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.2.ConvLSTM.0.cell.bias\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.cell.kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.cell.recurrent_kernel\n",
      "WARNING:tensorflow:Unresolved object in checkpoint: (root).DownLayers.3.ConvLSTM.0.cell.bias\n",
      "WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "for m in models:\n",
    "    print('------', m, '------')\n",
    "    for i in data_ids:\n",
    "        print(i)\n",
    "        p = subprocess.run(\n",
    "            ['python', os.path.join(code_seg, 'Inference2D.py'),\n",
    "             '--gpu', '0',\n",
    "             '--model_path', os.path.join(seg_model_dir, m),\n",
    "             '--sequence_path', os.path.join(data_dir, m, i),\n",
    "             '--output_path', os.path.join(data_dir, m, f'{i}_SEG_RES'),\n",
    "             '--edge_dist', edge_dist,\n",
    "             '--min_cell_size', min_size,\n",
    "             '--max_cell_size', max_size,\n",
    "             '--fov', fov,\n",
    "             '--centers_sigmoid_threshold', sigmoid_thresh,\n",
    "             '--min_center_size', min_center_size,\n",
    "             '--pre_sequence_frames', pre_sequence_frames,\n",
    "             '--data_format', data_format,\n",
    "            #  '--save_intermediate',\n",
    "            #  '--save_intermediate_path', os.path.join(data_dir, m, f'{i}_SEG_intermediate')\n",
    "            ],\n",
    "            stdout=subprocess.PIPE,\n",
    "            stderr=subprocess.PIPE)\n",
    "\n",
    "        print(p.stdout.decode(\"utf-8\").strip())\n",
    "        print(p.stderr.decode(\"utf-8\").strip())\n",
    "        print('\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7003e688-65cc-4fd9-a8ae-0193533758fb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gnn-tf",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
